version: 2
updates:
  # 1 NPM – tylko bezpośrednie zależności
  - package-ecosystem: "npm"
    directory: "/documentation/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    open-pull-requests-limit: 10
    groups:
      docusaurus:
        patterns:
          - "@docusaurus/*"
        update-types:
          - "minor"
          - "patch"

      docusaurus-major:
        patterns:
          - "@docusaurus/*"
        update-types:
          - "major"

      react:
        patterns:
          - "react"
          - "react-dom"
 
  # 2 GitHub Actions – aktualizacje workflowów
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
 